os: osx
    
language: ruby # mark.gg deploys are driven by rake

cache: bundler

# http://stackoverflow.com/a/16638729/265791
before_script:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    
script: bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "70911eb7cb63"
  - COMMIT_AUTHOR_EMAIL: "mark.cerqueira@gmail.com"