os: osx
    
language: ruby # mark.gg deploys are driven by rake

rvm:
  - 2.0.0p648

script: bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "70911eb7cb63"
  - COMMIT_AUTHOR_EMAIL: "mark.cerqueira@gmail.com"