os: osx

language: ruby

rvm:
  - 2.2.5

# Cache the gems we pull so subsequent builds are faster
cache: bundler

sudo: false

# We don't ever need to go deeper when publishing
git:
  depth: 1

# http://stackoverflow.com/a/16638729/265791
before_script:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    
script: bash ./deploy.sh

# This magic allows for pushing to GitHub via SSH
env:
  global:
  - ENCRYPTION_LABEL: "70911eb7cb63"
  - COMMIT_AUTHOR_EMAIL: "mark.cerqueira@gmail.com"
