# Include vendor to fix: https://github.com/jekyll/jekyll/issues/2938
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "vendor"]

# For Keybase verification
# https://github.com/keybase/keybase-issues/issues/366#issuecomment-38749201
include: [".well-known"]

plugins:
  - jekyll-gist
  - jekyll-sitemap
  
permalink: pretty

markdown: kramdown
kramdown:  
  input: GFM
  
title : mark cerqueira
tagline: well-rounded nerd
baseurl: ''

images2017 : "/assets/posts/2017"
images2018 : "/assets/posts/2018"
images2019 : "/assets/posts/2019"
images2020 : "/assets/posts/2020"

author :
  name : Mark Cerqueira
  email : mark@mark.gg
  github : markcerqueira
  twitter : markmcerqueira
  
managing_management: <i>Managing Management is a series on systems that are shareable and serve as actionable templates for addressing the deluge of things managers encounter everyday. Enjoyed this post and want to see more? Check out more at <a href="/archive/#managing+management">Managing Management</a>!</i>

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
JB :
  analytics :
    provider : google
    google : 
        tracking_id : 'UA-40706724-1'
